[tool]
[tool.poetry]
authors = ["Anuj Soni <anuj.soni97@outlook.com>"]
name = "root"
version = "0.0.0"
description= "False"
[tool.poetry.dependencies]
pandas = "*"
python = "^3.8"
seaborn = "*"
matplotlib = "3.1.3"
